TTLocalizer: Running in language: English
OTPLocalizer: Running in language: English
Traceback (most recent call last):
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\src\dependencies\panda\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\src\dependencies\panda\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\src\toontown\toonbase\ClientStart.py", line 126, in <module>
    ToonBase.ToonBase()
  File "toontown\toonbase\ToonBase.py", line 160, in __init__
    self.loader = ToontownLoader.ToontownLoader(self)
  File "toontown\toonbase\ToontownLoader.py", line 14, in __init__
    self.loadingScreen = ToontownLoadingScreen.ToontownLoadingScreen()
  File "toontown\toontowngui\ToontownLoadingScreen.py", line 22, in __init__
    scale=(logoScale * 2.0, 1, logoScale))
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\src\dependencies\panda\direct\gui\OnscreenImage.py", line 49, in __init__
    self.setImage(image, parent = parent, sort = sort)
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\src\dependencies\panda\direct\gui\OnscreenImage.py", line 106, in setImage
    tex = loader.loadTexture(image)
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\src\dependencies\panda\direct\showbase\Loader.py", line 623, in loadTexture
    raise IOError, message
IOError: Could not load texture: phase_3/maps/toontown-logo.png
